[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    ESP32-audioI2S
    ArduinoJson
    WiFiManager
    NTPClient
    Time
upload_speed = 921600
